
services:
  
  otelcol:
    image: otel/opentelemetry-collector-contrib:0.109.0
    command: ["--config=/etc/otel-collector-config.yml"]
    container_name: otelcol
    environment:
      - ENVIRONMENT=production
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - 4317:4317
      - 4318:4318
    networks:
      - app-network

  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.15.0
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - QUERY_UI_CONFIG_PATH=/etc/jaeger/ui-config.json
    volumes:
      - ./jaeger-ui-config.json:/etc/jaeger/ui-config.json
      - ./jaeger-custom-theme.css:/jaeger-ui/custom-theme.css
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14317:4317"
      - "14318:4318"
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:v3.4.2
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-otlp-receiver
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - app-network

################## automatic instrumentation setup ######################
  todobackend-springboot-automatic-instrumentation:
    container_name: todobackend-springboot-automatic-instrumentation
    build:
      context: ./automatic-instrumentation/todobackend-springboot
      dockerfile: Dockerfile
    profiles:
      - automatic-instrumentation
    ports:
      - "8080:8080"
    volumes:
      - ./automatic-instrumentation/todobackend-springboot:/app
    environment:
      - JAVA_OPTS=-Xmx512m -Xms512m
      - OTEL_SERVICE_NAME=todobackend-springboot
      - OTEL_RESOURCE_ATTRIBUTES=service.instance.id=todobackend-springboot,deployment.environment=dev
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4317
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - jaeger


  todoui-flask-automatic-instrumentation:
    container_name: todoui-flask-automatic-instrumentation
    build:
      context: ./automatic-instrumentation/todoui-flask
      dockerfile: Dockerfile
    profiles:
      - automatic-instrumentation
    ports:
      - "7000:7000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./automatic-instrumentation/todoui-flask:/app
    environment:
      - BACKEND_URL=http://todobackend-springboot-automatic-instrumentation:8080/todos/
      - OTEL_SERVICE_NAME=todoui-flask
      - OTEL_RESOURCE_ATTRIBUTES="service.instance.id=todoui-flask,deployment.environment=dev"
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4317
      - FLASK_ENV=production
      - FLASK_APP=app.py
    networks:
      - app-network
    depends_on:
      jaeger:
        condition: service_started
      todobackend-springboot-automatic-instrumentation:
        condition: service_healthy


################## automatic instrumentation setup ######################
  todobackend-springboot-custom-automatic-instrumentation:
    container_name: todobackend-springboot-custom-automatic-instrumentation
    build:
      context: ./custom-automatic-instrumentation/todobackend-springboot
      dockerfile: Dockerfile
    profiles:
      - custom-automatic-instrumentation
    ports:
      - "8080:8080"
    volumes:
      - ./custom-automatic-instrumentation/todobackend-springboot:/app
    environment:
      - JAVA_OPTS=-Xmx512m -Xms512m
      - OTEL_SERVICE_NAME=todobackend-springboot
      - OTEL_RESOURCE_ATTRIBUTES=service.instance.id=todobackend-springboot,deployment.environment=dev
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4317
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - jaeger

  todoui-flask-custom-automatic-instrumentation:
    container_name: todoui-flask-custom-automatic-instrumentation
    build:
      context: ./custom-automatic-instrumentation/todoui-flask
      dockerfile: Dockerfile
    profiles:
      - custom-automatic-instrumentation
    ports:
      - "7000:7000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./custom-automatic-instrumentation/todoui-flask:/app
    environment:
      - BACKEND_URL=http://todobackend-springboot-custom-automatic-instrumentation:8080/todos/
      - OTEL_SERVICE_NAME=todoui-flask
      - OTEL_RESOURCE_ATTRIBUTES="service.instance.id=todoui-flask,deployment.environment=dev"
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4317
      - FLASK_ENV=production
      - FLASK_APP=app.py
    networks:
      - app-network
    depends_on:
      jaeger:
        condition: service_started
      todobackend-springboot-custom-automatic-instrumentation:
        condition: service_healthy

################## manual instrumentation setup ######################
  echo:
    image: ealen/echo-server:0.9.2
    ports:
      - 6000:80
    environment:
      - OTEL_SERVICE_NAME=echo
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otpĺ
      - OTEL_LOGS_EXPORTER=otpl
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    networks:
      - app-network

  userbackend-flask-manual-instrumentation:
    container_name: userbackend-flask-manual-instrumentation
    build: 
      context: manual-instrumentation/userbackend-flask
      dockerfile: Dockerfile
    profiles:
      - manual-instrumentation
    volumes:
      - ./manual-instrumentation/userbackend-flask:/app
    environment:
      - OTEL_SERVICE_NAME=userbackend-flask
      - OTEL_RESOURCE_ATTRIBUTES="service.instance.id=userbackend-flask,deployment.environment=dev
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4317
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - PORT=7000
    ports:
      - 7000:7000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - app-network
    depends_on:
      otelcol:
        condition: service_started  

networks:
  app-network:
    driver: bridge
