server.port=8080

server.forward-headers-strategy=native
management.endpoints.web.exposure.include=*

spring.profiles.active=dev

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.application.name=springboot-backend 
otel.exporter.otlp.endpoint=http://${COLLECTOR_HOST:localhost}:4317
